
require 'config.colorscheme'
require 'config.nvimtree'
require 'config.telescope'
require 'config.lualine'
require 'config.cmp'
require 'config.lsp'
require 'config.rust_tools'
require 'config.trouble'
require 'config.vgit'
require 'config.lsp_installer'
require 'config.which_key'
require 'config.treesitter'
require 'config.lsp_saga'

