require "plugins.config.lualine"
require "plugins.config.indentline"
require "plugins.config.gitsigns"
require "plugins.config.fzf"
require "plugins.config.lsp"
require "plugins.config.cmp"
require "plugins.config.treesitter"
require "plugins.config.todo"
